version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - "php"
        volumes:
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "$PWD:/var/www/uvdesk"
        container_name: "compose-nginx"
    php:
        image: php:7.4-fpm
        ports:
            - "9000:9000"
        volumes:
            - "$PWD:/var/www/uvdesk"
        container_name: "compose-php"
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=testpassword
        container_name: "compose-mysql"
