<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNGxBdg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNGxBdg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSNGxBdg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSNGxBdg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSNGxBdg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SNGxBdg',
    'container.build_id' => 'b72c0a04',
    'container.build_time' => 1637309530,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNGxBdg');
